version: "3"
services:
    db:
        image: postgres:14
        container_name: postgres
        restart: always
        expose:
            - "5432"
        volumes:
            - ./data:/var/lib/postgresql/data
            # - postgres-volume:/var/lib/postgresql/data
        #   - ./pg-init-scripts:/docker-entrypoint-initdb.d
        env_file:
            - .env
        # tty: true
        networks:
            - docker-network

    frontend:
        # depends_on: backend
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: react:42t
        ports:
            - "3000:3000"
        volumes:
            - /app/node_modules
    
    backend:
        depends_on:
            - db
        healthcheck:
            test:
                [
                    "CMD",
                    "psql",
                    "-U",
                    "${POSTGRES_USER}",
                    "-c",
                    "SELECT 1",
                    "-d",
                    "${POSTGRES_DB}",
                    "-h",
                    "${POSTGRES_HOST}",
                    "-p",
                    "${POSTGRES_PORT}",
                ]
            interval: 30s
            timeout: 10s
            retries: 5
        container_name: backend
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: node:42t
        ports:
            - "5001:5001"
        volumes:
            - /app/node_modules
        networks:
            - docker-network

networks:
    docker-network:
        name: docker-network
        driver: bridge
# volumes:
#   postgres-volume:
#     name: postgres-volume
#     driver: local
#     driver-opts:
#       type: none
#       device: ./docker/postgres
#       o: bind
