version: "3"
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    expose:
      - "5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - docker-network
  frontend:
    container_name: frontend
    build:
        context: ./frontend
        dockerfile: Dockerfile
    image: frontend
    ports:
        - "3000:3000"
    volumes:
        - ./frontend:/app
        - /app/node_modules

  backend:
    depends_on:
      - db
    container_name: backend
    build:
        context: ./backend
        dockerfile: Dockerfile
    image: backend
    ports:
        - "5001:5001"
    volumes:
        - ./backend:/app
        - /app/node_modules
    networks:
      - docker-network
networks:
  docker-network:
    name: docker-network
    driver: bridge
