version: "3"
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: 42T
    volumes:
      - ./data:/var/lib/postgresql/data